databases:
  - name: referencial-db
    databaseName: referencial
    user: referencial
    plan: free

services:
  # Serviço Web (Django + Gunicorn)
  - type: web
    name: referencial-web
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t referencial-app .
    startCommand: python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8000 config.asgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ASGI_THREADS
        value: "4"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: REFERENCIAL_DATABASE_URL
        fromDatabase:
          name: referencial-db
          property: connectionString
      - key: REFERENCIAL_REDIS_URL
        fromService:
          type: redis
          name: referencial-redis
          property: connectionString
      - key: MEDIA_BACKEND
        value: s3
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
    dockerfilePath: ./Dockerfile

  # Worker Celery (Processamento de Assíncrono)
  - type: worker
    name: referencial-worker
    env: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    startCommand: celery -A config worker -l info --concurrency=1 --prefetch-multiplier=1 --max-tasks-per-child=1 --max-memory-per-child=300000
    envVars:
      - key: REFERENCIAL_DATABASE_URL
        fromDatabase:
          name: referencial-db
          property: connectionString
      - key: REFERENCIAL_REDIS_URL
        fromService:
          type: redis
          name: referencial-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false # Deve ser copiado manualmente ou usar sync: false e definir no dashboard se quiser a mesma key
      - key: DJANGO_DEBUG
        value: "False"
      - key: MALLOC_ARENA_MAX
        value: "2"
      - key: MEDIA_BACKEND
        value: s3
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false

  # Redis (Broker para Celery e Channels)
  - type: redis
    name: referencial-redis
    region: oregon
    plan: free
    ipAllowList: [] # Apenas serviços internos
