# Generated by Django 5.1.13 on 2025-11-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_audit_cliente_37c01d_idx_core_auditl_cliente_c6c50f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientetema',
            name='meb_avatar_url',
            field=models.URLField(blank=True),
        ),
    ]
