# Generated by Django 5.1.13 on 2025-11-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersessionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersessionlog',
            name='device',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersessionlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
    ]
