# Generated by Codex
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usersessionlog_device_usersessionlog_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('origem_tipo', models.CharField(max_length=50)),
                ('origem_id', models.CharField(blank=True, max_length=64)),
                ('tarefa_id', models.IntegerField(blank=True, null=True)),
                ('pontos', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoreentrys', to='core.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
            },
        ),
        migrations.AddIndex(
            model_name='scoreentry',
            index=models.Index(fields=['cliente', 'usuario', 'created_at'], name='core_scoree_cliente_usu_49f9df_idx'),
        ),
        migrations.AddIndex(
            model_name='scoreentry',
            index=models.Index(fields=['cliente', 'origem_tipo', 'origem_id'], name='core_scoree_cliente_ori_2dcb20_idx'),
        ),
    ]
