# Generated by Django 5.1.13 on 2026-01-06 02:20

import django.db.models.deletion
from django.db import migrations, models


def _rename_index_if_supported(old_name: str, new_name: str):
    def forwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')

    def backwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}";')

    return migrations.RunPython(forwards, backwards)


def safe_rename_index(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            _rename_index_if_supported(old_name, new_name),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                old_name=old_name,
                new_name=new_name,
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scoreentry'),
    ]

    operations = [
        safe_rename_index('scoreentry', 'core_scoree_cliente_usu_49f9df_idx', 'core_scoree_cliente_1cb5ea_idx'),
        safe_rename_index('scoreentry', 'core_scoree_cliente_ori_2dcb20_idx', 'core_scoree_cliente_7c5465_idx'),
        migrations.AlterField(
            model_name='scoreentry',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
