# Generated by Django 5.1.13 on 2026-01-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_scoreentry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scoreentry',
            new_name='core_scoree_cliente_1cb5ea_idx',
            old_name='core_scoree_cliente_usu_49f9df_idx',
        ),
        migrations.RenameIndex(
            model_name='scoreentry',
            new_name='core_scoree_cliente_7c5465_idx',
            old_name='core_scoree_cliente_ori_2dcb20_idx',
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='scoreentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
