# Generated by Codex

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_rename_core_scoree_cliente_usu_49f9df_idx_core_scoree_cliente_1cb5ea_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThrottleBlock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(max_length=100)),
                ("ident", models.CharField(blank=True, max_length=255)),
                ("cache_key", models.CharField(max_length=255, unique=True)),
                ("wait_seconds", models.IntegerField(default=0)),
                ("blocked_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="throttle_blocks",
                        to="core.cliente",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="throttle_blocks",
                        to="core.usuario",
                    ),
                ),
            ],
            options={
                "ordering": ("-blocked_until", "-created_at"),
            },
        ),
        migrations.AddIndex(
            model_name="throttleblock",
            index=models.Index(fields=["cliente", "blocked_until"], name="core_throt_cliente_40f676_idx"),
        ),
        migrations.AddIndex(
            model_name="throttleblock",
            index=models.Index(fields=["blocked_until"], name="core_throt_blocked_3b02b1_idx"),
        ),
    ]
