# Generated by Codex

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_enable_reviews_flag"),
        ("core", "0008_throttleblock"),
    ]

    operations = []
