# Generated by Django 5.1.5 on 2026-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0008_enable_reviews_flag_0008_throttleblock'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='throttleblock',
            new_name='core_thrott_cliente_4c9d39_idx',
            old_name='core_throt_cliente_40f676_idx',
        ),
        migrations.RenameIndex(
            model_name='throttleblock',
            new_name='core_thrott_blocked_c6fdc0_idx',
            old_name='core_throt_blocked_3b02b1_idx',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_cliente', 'Admin do Cliente'), ('articulador', 'Redator'), ('membro_gt', 'Membro GT'), ('leitor', 'Leitor')], default='leitor', max_length=20),
        ),
    ]
