# Generated by Django 5.1.5 on 2026-01-26 10:22

from django.db import migrations, models


def _rename_index_if_supported(old_name: str, new_name: str):
    def forwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')

    def backwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}";')

    return migrations.RunPython(forwards, backwards)


def safe_rename_index(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            _rename_index_if_supported(old_name, new_name),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                old_name=old_name,
                new_name=new_name,
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_0008_enable_reviews_flag_0008_throttleblock'),
    ]

    operations = [
        safe_rename_index('throttleblock', 'core_throt_cliente_40f676_idx', 'core_thrott_cliente_4c9d39_idx'),
        safe_rename_index('throttleblock', 'core_throt_blocked_3b02b1_idx', 'core_thrott_blocked_c6fdc0_idx'),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_cliente', 'Admin do Cliente'), ('articulador', 'Redator'), ('membro_gt', 'Membro GT'), ('leitor', 'Leitor')], default='leitor', max_length=20),
        ),
    ]
