# Generated by Django 5.1.13 on 2026-01-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_core_throt_cliente_40f676_idx_core_thrott_cliente_4c9d39_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin_cliente', 'Admin do Cliente'), ('articulador', 'Redator'), ('revisor', 'Revisor'), ('membro_gt', 'Membro GT'), ('leitor', 'Leitor')], default='leitor', max_length=20),
        ),
    ]
