# Generated by Django 5.1.13 on 2026-03-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0010_escola"),
        ("core", "0011_alter_usuario_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="escola",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="curriculum.escola",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin_cliente", "Admin do Cliente"),
                    ("diretor", "Diretor"),
                    ("coordenador_pedagogico", "Coordenador Pedagógico"),
                    ("professor", "Professor"),
                    ("articulador", "Redator"),
                    ("revisor", "Revisor"),
                    ("membro_gt", "Membro GT"),
                    ("leitor", "Leitor"),
                ],
                default="leitor",
                max_length=30,
            ),
        ),
    ]
