# Generated by Django 5.1.13 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_usuario_escola_and_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="seguimento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("profissional_apoio", "Profissional de Apoio"),
                    ("professor_anos_iniciais", "Professor - Anos Iniciais"),
                    ("professor_anos_finais", "Professor - Anos Finais"),
                    ("professor_eja", "Professor - EJA"),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
