# Generated by Django 5.1.6 on 2026-04-06 19:29

import django.db.models.deletion
from django.db import migrations, models


TIPOS_PADRAO = (
    {
        "slug": "diretor",
        "nome": "Diretor",
        "role_interno": "diretor",
        "seguimento": "",
        "acesso_ppp": "editar",
        "exibir_no_cadastro": True,
        "ativo": True,
        "ordem_exibicao": 10,
    },
    {
        "slug": "coordenador-pedagogico",
        "nome": "Coordenador Pedagógico",
        "role_interno": "coordenador_pedagogico",
        "seguimento": "",
        "acesso_ppp": "editar",
        "exibir_no_cadastro": True,
        "ativo": True,
        "ordem_exibicao": 20,
    },
    {
        "slug": "professor-geral",
        "nome": "Professor",
        "role_interno": "professor",
        "seguimento": "",
        "acesso_ppp": "visualizar",
        "exibir_no_cadastro": False,
        "ativo": True,
        "ordem_exibicao": 30,
    },
    {
        "slug": "profissional-apoio",
        "nome": "Profissional de Apoio",
        "role_interno": "professor",
        "seguimento": "profissional_apoio",
        "acesso_ppp": "visualizar",
        "exibir_no_cadastro": True,
        "ativo": True,
        "ordem_exibicao": 40,
    },
    {
        "slug": "professor-anos-iniciais",
        "nome": "Professor - Anos Iniciais",
        "role_interno": "professor",
        "seguimento": "professor_anos_iniciais",
        "acesso_ppp": "visualizar",
        "exibir_no_cadastro": True,
        "ativo": True,
        "ordem_exibicao": 50,
    },
    {
        "slug": "professor-anos-finais",
        "nome": "Professor - Anos Finais",
        "role_interno": "professor",
        "seguimento": "professor_anos_finais",
        "acesso_ppp": "visualizar",
        "exibir_no_cadastro": True,
        "ativo": True,
        "ordem_exibicao": 60,
    },
    {
        "slug": "professor-eja",
        "nome": "Professor - EJA",
        "role_interno": "professor",
        "seguimento": "professor_eja",
        "acesso_ppp": "visualizar",
        "exibir_no_cadastro": True,
        "ativo": True,
        "ordem_exibicao": 70,
    },
)


def _criar_tipos_padrao(apps, schema_editor):
    Cliente = apps.get_model("core", "Cliente")
    TipoUsuarioCadastro = apps.get_model("core", "TipoUsuarioCadastro")
    Usuario = apps.get_model("core", "Usuario")

    for cliente in Cliente.objects.all():
        for item in TIPOS_PADRAO:
            TipoUsuarioCadastro.objects.update_or_create(
                cliente_id=cliente.id,
                slug=item["slug"],
                defaults={
                    "nome": item["nome"],
                    "role_interno": item["role_interno"],
                    "seguimento": item["seguimento"],
                    "acesso_ppp": item["acesso_ppp"],
                    "exibir_no_cadastro": item["exibir_no_cadastro"],
                    "ativo": item["ativo"],
                    "ordem_exibicao": item["ordem_exibicao"],
                },
            )

        tipos_do_cliente = {
            (tipo.role_interno, tipo.seguimento or ""): tipo.id
            for tipo in TipoUsuarioCadastro.objects.filter(cliente_id=cliente.id, ativo=True)
        }
        professor_geral_id = TipoUsuarioCadastro.objects.filter(
            cliente_id=cliente.id,
            slug="professor-geral",
        ).values_list("id", flat=True).first()

        for usuario in Usuario.objects.filter(cliente_id=cliente.id, tipo_cadastro_id__isnull=True):
            tipo_id = tipos_do_cliente.get((usuario.role, usuario.seguimento or ""))
            if tipo_id is None:
                tipo_id = tipos_do_cliente.get((usuario.role, ""))
            if tipo_id is None and usuario.role == "professor":
                tipo_id = professor_geral_id
            if tipo_id:
                usuario.tipo_cadastro_id = tipo_id
                usuario.save(update_fields=["tipo_cadastro"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuario_seguimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuarioCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('role_interno', models.CharField(choices=[('diretor', 'Diretor'), ('coordenador_pedagogico', 'Coordenador PedagÃ³gico'), ('professor', 'Professor')], max_length=30)),
                ('seguimento', models.CharField(blank=True, choices=[('profissional_apoio', 'Profissional de Apoio'), ('professor_anos_iniciais', 'Professor - Anos Iniciais'), ('professor_anos_finais', 'Professor - Anos Finais'), ('professor_eja', 'Professor - EJA')], default='', help_text='Opcional. Use apenas para mapear tipos de professor aos seguimentos legados do AVA.', max_length=40)),
                ('acesso_ppp', models.CharField(choices=[('editar', 'Pode editar'), ('visualizar', 'Apenas visualizar')], default='visualizar', max_length=20)),
                ('exibir_no_cadastro', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem_exibicao', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Tipo de UsuÃ¡rio de Cadastro',
                'verbose_name_plural': 'Tipos de UsuÃ¡rio de Cadastro',
                'ordering': ('ordem_exibicao', 'nome'),
                'unique_together': {('cliente', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.tipousuariocadastro'),
        ),
        migrations.RunPython(_criar_tipos_padrao, migrations.RunPython.noop),
    ]
