# Generated by Django 5.2.11 on 2026-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20260410_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipousuariocadastro',
            options={'ordering': ('ordem_exibicao', 'nome'), 'verbose_name': 'Tipo de Usuário de Cadastro', 'verbose_name_plural': 'Tipos de Usuário de Cadastro'},
        ),
        migrations.AlterField(
            model_name='tipousuariocadastro',
            name='role_interno',
            field=models.CharField(choices=[('diretor', 'Diretor'), ('coordenador_pedagogico', 'Coordenador Pedagógico'), ('professor', 'Professor')], max_length=30),
        ),
    ]
