# Generated by Django 5.2.11 on 2026-06-08 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_redundant_indexes_add_gt_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibicao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Eixo',
                'verbose_name_plural': 'Eixos',
                'ordering': ('ordem_exibicao', 'nome'),
                'unique_together': {('cliente', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='eixos',
            field=models.ManyToManyField(blank=True, help_text='Eixos que este usuario pode acessar no AVA.', related_name='usuarios', to='core.eixo', verbose_name='Eixos AVA'),
        ),
    ]
