# Generated by Django 5.0.2 on 2026-02-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('core', '0011_alter_usuario_role'),
        ('courses', '0002_avaliacaoplano_planoaula_rubrica_rubricacriterio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planopublicado',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes_banco', to='courses.planoaula'),
        ),
        migrations.AddField(
            model_name='planopublicado',
            name='publicado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_publicados_banco', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planopublicadoavaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_banco', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planopublicadoavaliacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='planopublicadoavaliacao',
            name='plano_publicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='bank.planopublicado'),
        ),
        migrations.AddField(
            model_name='planopublicadocomentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_banco', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planopublicadocomentario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='planopublicadocomentario',
            name='plano_publicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='bank.planopublicado'),
        ),
        migrations.AddIndex(
            model_name='planopublicado',
            index=models.Index(fields=['cliente', 'status_curadoria', 'visibilidade'], name='bank_planop_cliente_9b1795_idx'),
        ),
        migrations.AddIndex(
            model_name='planopublicado',
            index=models.Index(fields=['cliente', 'data_publicacao'], name='bank_planop_cliente_2ca62d_idx'),
        ),
        migrations.AddIndex(
            model_name='planopublicadoavaliacao',
            index=models.Index(fields=['cliente', 'plano_publicado'], name='bank_planop_cliente_c4a234_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planopublicadoavaliacao',
            unique_together={('plano_publicado', 'avaliador')},
        ),
        migrations.AddIndex(
            model_name='planopublicadocomentario',
            index=models.Index(fields=['cliente', 'plano_publicado'], name='bank_planop_cliente_e5746e_idx'),
        ),
    ]
