# Generated by Django 5.1.13 on 2025-10-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comentario',
            new_name='comments_co_cliente_a0f7cf_idx',
            old_name='comments_co_client_5c71c2_idx',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
    ]
