# Generated by Django 5.1.5 on 2026-03-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_comments_co_client_5c71c2_idx_comments_co_cliente_a0f7cf_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='alvo_tipo',
            field=models.CharField(choices=[('resposta', 'Resposta'), ('texto_unico', 'Texto Único'), ('quadro', 'Quadro'), ('ppp', 'PPP')], max_length=20),
        ),
    ]
