# Generated by Django 5.1.5 on 2026-03-13 19:22

from django.db import migrations


def safe_rename_index(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunSQL(
                sql=f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";',
                reverse_sql=f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}";',
            ),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                old_name=old_name,
                new_name=new_name,
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividade',
            options={'ordering': ['aula'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
        migrations.AlterModelOptions(
            name='atividadetentativa',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Tentativa de Atividade', 'verbose_name_plural': 'Tentativas de Atividades'},
        ),
        migrations.AlterModelOptions(
            name='aula',
            options={'ordering': ['modulo', 'ordem'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='conteudoaula',
            options={'ordering': ['aula', 'ordem'], 'verbose_name': 'Conteúdo de Aula', 'verbose_name_plural': 'Conteúdos de Aula'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-created_at'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='cursocategoria',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Curso', 'verbose_name_plural': 'Categorias de Curso'},
        ),
        migrations.AlterModelOptions(
            name='cursomodulo',
            options={'ordering': ['curso', 'ordem'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='quizalternativa',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='quizquestao',
            options={'ordering': ['ordem'], 'verbose_name': 'Questão de Quiz', 'verbose_name_plural': 'Questões de Quiz'},
        ),
        migrations.AlterModelOptions(
            name='trilhaformativa',
            options={'ordering': ['ordem_exibicao', 'nome'], 'verbose_name': 'Trilha Formativa', 'verbose_name_plural': 'Trilhas Formativas'},
        ),
        safe_rename_index('atividadetentativa', 'ava_ativtent_cli_alu_ati_idx', 'ava_ativida_cliente_78e269_idx'),
        safe_rename_index('certificado', 'ava_cert_cli_cod_idx', 'ava_certifi_cliente_49fcdd_idx'),
        safe_rename_index('certificado', 'ava_cert_cli_alu_idx', 'ava_certifi_cliente_0e7d1c_idx'),
        safe_rename_index('curso', 'ava_curso_cli_sta_abr_idx', 'ava_curso_cliente_971dd2_idx'),
        safe_rename_index('curso', 'ava_curso_slug_idx', 'ava_curso_slug_502f07_idx'),
        safe_rename_index('matriculacurso', 'ava_matcurso_cli_alu_cur_idx', 'ava_matricu_cliente_a00e1f_idx'),
        safe_rename_index('matriculacurso', 'ava_matcurso_status_idx', 'ava_matricu_status_575b09_idx'),
        safe_rename_index('matriculatrilha', 'ava_mattrilha_cli_alu_tri_idx', 'ava_matricu_cliente_8966aa_idx'),
        safe_rename_index('progressoaula', 'ava_progaula_cli_mat_aul_idx', 'ava_progres_cliente_2d9e54_idx'),
    ]
