# Generated by Django 5.2.11 on 2026-03-30 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0002_alter_atividade_options_and_more'),
        ('core', '0012_usuario_escola_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz Objetivo'), ('tarefa', 'Tarefa Discursiva'), ('envio_arquivo', 'Envio de Arquivo'), ('questionario', 'Questionário Simples (Pesquisa)'), ('reflexao', 'Reflexão Guiada'), ('forum', 'Forum Interativo')], max_length=30, verbose_name='Tipo da Atividade'),
        ),
        migrations.CreateModel(
            name='AtividadeForumMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('texto', models.TextField(blank=True, verbose_name='Mensagem')),
                ('editado_em', models.DateTimeField(blank=True, null=True, verbose_name='Editado em')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_forum', to='ava.atividade')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_forum_ava', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('resposta_para', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='ava.atividadeforummensagem')),
            ],
            options={
                'verbose_name': 'Mensagem de Forum',
                'verbose_name_plural': 'Mensagens de Forum',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeForumAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('arquivo', models.FileField(upload_to='ava/forum/anexos/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ava.atividadeforummensagem')),
            ],
            options={
                'verbose_name': 'Anexo de Mensagem do Forum',
                'verbose_name_plural': 'Anexos de Mensagens do Forum',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='atividadeforummensagem',
            index=models.Index(fields=['cliente', 'atividade', 'created_at'], name='ava_ativida_cliente_85916b_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeforummensagem',
            index=models.Index(fields=['cliente', 'autor', 'created_at'], name='ava_ativida_cliente_d5dd52_idx'),
        ),
        migrations.AddIndex(
            model_name='atividadeforumanexo',
            index=models.Index(fields=['cliente', 'created_at'], name='ava_ativida_cliente_55cf00_idx'),
        ),
    ]
