# Generated by Django 5.1.15 on 2026-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0004_corrigir_acentuacao_textos_ava'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadeforumanexo',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Anexo de Mensagem do Fórum', 'verbose_name_plural': 'Anexos de Mensagens do Fórum'},
        ),
        migrations.AlterModelOptions(
            name='atividadeforummensagem',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Mensagem de Fórum', 'verbose_name_plural': 'Mensagens de Fórum'},
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz Objetivo'), ('tarefa', 'Tarefa Discursiva'), ('envio_arquivo', 'Envio de Arquivo'), ('questionario', 'Questionário Simples (Pesquisa)'), ('reflexao', 'Reflexão Guiada'), ('forum', 'Fórum Interativo')], max_length=30, verbose_name='Tipo da Atividade'),
        ),
    ]
