# Generated by Django 5.1.15 on 2026-05-28 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0004_corrigir_acentuacao_textos_ava'),
        ('core', '0017_remove_redundant_indexes_add_gt_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadeforumanexo',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Anexo de Mensagem do Fórum', 'verbose_name_plural': 'Anexos de Mensagens do Fórum'},
        ),
        migrations.AlterModelOptions(
            name='atividadeforummensagem',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Mensagem de Fórum', 'verbose_name_plural': 'Mensagens de Fórum'},
        ),
        migrations.AlterField(
            model_name='atividade',
            name='tipo',
            field=models.CharField(choices=[('quiz', 'Quiz Objetivo'), ('tarefa', 'Tarefa Discursiva'), ('envio_arquivo', 'Envio de Arquivo'), ('questionario', 'Questionário Simples (Pesquisa)'), ('reflexao', 'Reflexão Guiada'), ('forum', 'Fórum Interativo')], max_length=30, verbose_name='Tipo da Atividade'),
        ),
        migrations.AlterField(
            model_name='atividadetentativa',
            name='arquivo_enviado',
            field=models.FileField(blank=True, null=True, upload_to='ava/tentativas/arquivos/', verbose_name='Arquivo Enviado (legado)'),
        ),
        migrations.CreateModel(
            name='AtividadeTentativaArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('arquivo', models.FileField(upload_to='ava/tentativas/arquivos/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome original')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('tentativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='ava.atividadetentativa')),
            ],
            options={
                'verbose_name': 'Arquivo de Tentativa',
                'verbose_name_plural': 'Arquivos de Tentativas',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
