# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ava", "0006_merge_0005_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conteudoaula",
            name="arquivo",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="ava/aulas/arquivos/",
                verbose_name="Arquivo/PDF/Mídia",
            ),
        ),
    ]
