# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ava", "0007_alter_conteudoaula_arquivo_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="imagem_display",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="ava/aulas/imagens/",
                verbose_name="Imagem de exibição",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="imagem_posicao",
            field=models.CharField(
                choices=[("acima", "Acima do texto"), ("abaixo", "Abaixo do texto")],
                default="acima",
                max_length=10,
                verbose_name="Posição da imagem",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="imagem_largura_percent",
            field=models.PositiveIntegerField(
                default=100,
                verbose_name="Largura da imagem (%)",
            ),
        ),
        migrations.AddField(
            model_name="aula",
            name="imagem_alinhamento",
            field=models.CharField(
                choices=[
                    ("esquerda", "Esquerda"),
                    ("centro", "Centro"),
                    ("direita", "Direita"),
                ],
                default="centro",
                max_length=10,
                verbose_name="Alinhamento da imagem",
            ),
        ),
        migrations.AddField(
            model_name="conteudoaula",
            name="imagem_display",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="ava/aulas/imagens/",
                verbose_name="Imagem de exibição",
            ),
        ),
        migrations.AddField(
            model_name="conteudoaula",
            name="imagem_posicao",
            field=models.CharField(
                choices=[("acima", "Acima do texto"), ("abaixo", "Abaixo do texto")],
                default="acima",
                max_length=10,
                verbose_name="Posição da imagem",
            ),
        ),
        migrations.AddField(
            model_name="conteudoaula",
            name="imagem_largura_percent",
            field=models.PositiveIntegerField(
                default=100,
                verbose_name="Largura da imagem (%)",
            ),
        ),
        migrations.AddField(
            model_name="conteudoaula",
            name="imagem_alinhamento",
            field=models.CharField(
                choices=[
                    ("esquerda", "Esquerda"),
                    ("centro", "Centro"),
                    ("direita", "Direita"),
                ],
                default="centro",
                max_length=10,
                verbose_name="Alinhamento da imagem",
            ),
        ),
    ]
