# Generated by Django 5.2.11 on 2026-06-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0008_aula_imagem_display_conteudoaula_imagem_display'),
        ('core', '0018_eixo_usuario_eixos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='eixos',
            field=models.ManyToManyField(blank=True, help_text='Se informado, apenas usuarios vinculados a pelo menos um destes eixos poderao acessar o curso.', related_name='ava_cursos', to='core.eixo', verbose_name='Eixos'),
        ),
    ]
