# Generated by Codex on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ava", "0009_curso_eixos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividadetentativa",
            name="arquivo_enviado",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="ava/tentativas/arquivos/",
                verbose_name="Arquivo Enviado (legado)",
            ),
        ),
        migrations.AlterField(
            model_name="atividadetentativaarquivo",
            name="arquivo",
            field=models.FileField(
                max_length=500,
                upload_to="ava/tentativas/arquivos/",
                verbose_name="Arquivo",
            ),
        ),
    ]
