# Generated by Django 5.2.11 on 2026-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0010_alter_atividade_tentativa_arquivo_paths'),
        ('core', '0018_eixo_usuario_eixos'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='eixos_restricao_roles',
            field=models.JSONField(blank=True, default=list, help_text='Se vazio, a restricao vale para todos os perfis nao administradores.', verbose_name='Perfis afetados pela restricao de eixos'),
        ),
        migrations.AddField(
            model_name='cursomodulo',
            name='eixos',
            field=models.ManyToManyField(blank=True, help_text='Se informado, restringe este modulo por eixo sem bloquear o curso inteiro.', related_name='ava_modulos', to='core.eixo', verbose_name='Eixos'),
        ),
        migrations.AddField(
            model_name='cursomodulo',
            name='eixos_restricao_roles',
            field=models.JSONField(blank=True, default=list, help_text='Se vazio, a restricao vale para todos os perfis nao administradores.', verbose_name='Perfis afetados pela restricao de eixos'),
        ),
    ]
