# Generated by Django 5.2.11 on 2026-06-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0011_curso_eixos_restricao_roles_cursomodulo_eixos_and_more'),
        ('core', '0018_eixo_usuario_eixos'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='eixos',
            field=models.ManyToManyField(blank=True, help_text='Se informado, restringe esta atividade por eixo sem bloquear o curso ou modulo inteiro.', related_name='ava_atividades', to='core.eixo', verbose_name='Eixos'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='eixos_restricao_roles',
            field=models.JSONField(blank=True, default=list, help_text='Se vazio, a restricao vale para todos os perfis nao administradores.', verbose_name='Perfis afetados pela restricao de eixos'),
        ),
    ]
