# Generated by Django 5.2.11 on 2026-07-29 18:16

import ava.models.followup
import ava.storage
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ava', '0014_atividade_bloqueio_manual'),
        ('core', '0020_usuario_ava_multimunicipio'),
        ('curriculum', '0012_remove_redundant_indexes_add_gt_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAcompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('categoria', models.CharField(choices=[('relatorio', 'Relatório'), ('frequencia', 'Frequência'), ('experiencia_exitosa', 'Experiência exitosa'), ('pratica_pedagogica', 'Prática pedagógica'), ('outro', 'Outro')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('periodo_referencia', models.DateField(blank=True, help_text='Use o primeiro dia do mês ou a data à qual o registro se refere.', null=True, verbose_name='Período de referência')),
                ('arquivo', models.FileField(max_length=500, storage=ava.storage.private_ava_storage, upload_to=ava.models.followup.acompanhamento_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'odt', 'xls', 'xlsx', 'ods', 'csv', 'jpg', 'jpeg', 'png'])])),
                ('nome_original', models.CharField(blank=True, max_length=255)),
                ('tamanho_bytes', models.PositiveBigIntegerField(default=0)),
                ('arquivado', models.BooleanField(default=False)),
                ('arquivado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Documento de acompanhamento',
                'verbose_name_plural': 'Documentos de acompanhamento',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='documentoacompanhamento',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_acompanhamento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoacompanhamento',
            name='arquivado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_acompanhamento_arquivados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoacompanhamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='documentoacompanhamento',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_acompanhamento_criados', to=settings.AUTH_USER_MODEL, verbose_name='Incluído por'),
        ),
        migrations.AddField(
            model_name='documentoacompanhamento',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_acompanhamento', to='ava.curso', verbose_name='Turma/curso'),
        ),
        migrations.AddField(
            model_name='documentoacompanhamento',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_acompanhamento', to='curriculum.escola'),
        ),
        migrations.AddIndex(
            model_name='documentoacompanhamento',
            index=models.Index(fields=['cliente', 'escola', 'arquivado'], name='ava_documen_cliente_617f75_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoacompanhamento',
            index=models.Index(fields=['cliente', 'curso', 'aluno'], name='ava_documen_cliente_035018_idx'),
        ),
        migrations.AddIndex(
            model_name='documentoacompanhamento',
            index=models.Index(fields=['cliente', 'categoria', 'periodo_referencia'], name='ava_documen_cliente_280226_idx'),
        ),
    ]
