# Generated by Django 5.1.13 on 2025-11-18 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_core_audit_cliente_37c01d_idx_core_auditl_cliente_c6c50f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MebThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meb_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thread do MEB',
                'verbose_name_plural': 'Threads do MEB',
                'ordering': ('-updated_at',),
                'unique_together': {('cliente', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='MebMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('origem', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Admin'), ('meb', 'MEB'), ('sistema', 'Sistema')], default='cliente', max_length=20)),
                ('conteudo', models.TextField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meb_messages', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='meb.mebthread')),
            ],
            options={
                'verbose_name': 'Mensagem do MEB',
                'verbose_name_plural': 'Mensagens do MEB',
                'ordering': ('created_at', 'id'),
            },
        ),
    ]
