# Generated by Django 5.1.5 on 2026-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicforms', '0002_alter_campodinamico_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostacampodinamico',
            name='owner_type',
            field=models.CharField(choices=[('resposta', 'Resposta'), ('texto_unico', 'Texto Único'), ('quadro', 'Quadro'), ('gt', 'GT')], max_length=20),
        ),
    ]
