# Generated by Django 5.1.5 on 2026-02-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dynamicforms", "0003_alter_respostacampodinamico_owner_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respostacampodinamico",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("resposta", "Resposta"),
                    ("texto_unico", "Texto Único"),
                    ("quadro", "Quadro"),
                    ("gt", "GT"),
                    ("curso_plano", "Curso Plano"),
                ],
                max_length=20,
            ),
        ),
    ]

