# Generated by Django 5.0.2 on 2026-02-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_alter_usuario_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('ppp', 'PPP'), ('referencial', 'Referencial')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo_html', models.TextField(blank=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documento_versoes', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('publicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_publicados', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicacoes', to='documents.documentoversao')),
            ],
            options={
                'ordering': ('-publicado_em',),
            },
        ),
        migrations.CreateModel(
            name='PlanoMetaPPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=80)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('eixo', models.CharField(blank=True, max_length=120)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.CreateModel(
            name='ReferencialHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('codigo', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('componente_curricular', models.CharField(blank=True, max_length=150)),
                ('etapa_modalidade', models.CharField(blank=True, max_length=150)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
            ],
            options={
                'ordering': ('codigo',),
            },
        ),
        migrations.AddIndex(
            model_name='documentoversao',
            index=models.Index(fields=['cliente', 'tipo', 'versao'], name='documents_d_cliente_16e3de_idx'),
        ),
        migrations.AddIndex(
            model_name='documentopublicacao',
            index=models.Index(fields=['cliente', 'publicado_em'], name='documents_d_cliente_9ec87c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planometappp',
            unique_together={('cliente', 'codigo')},
        ),
        migrations.AlterUniqueTogether(
            name='referencialhabilidade',
            unique_together={('cliente', 'codigo')},
        ),
    ]
