# Generated by Django 5.1.13 on 2025-10-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_audit_cliente_37c01d_idx_core_auditl_cliente_c6c50f_idx_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='revisao',
            new_name='reviews_rev_cliente_dd2ce1_idx',
            old_name='reviews_rev_client_61a71c_idx',
        ),
        migrations.AlterField(
            model_name='revisao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
    ]
