# Generated by Django 5.1.5 on 2026-01-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reviews_rev_client_61a71c_idx_reviews_rev_cliente_dd2ce1_idx_and_more'),
        ('reviews', '0002_reviewer_models'),
    ]

    operations = [
    ]
