# Generated by Django 5.1.13 on 2026-01-26 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_usuario_role'),
        ('reviews', '0003_merge_20260126_1134'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewdecision',
            new_name='reviews_rev_cliente_a27943_idx',
            old_name='reviews_rev_cliente_2f9a8f_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewdecision',
            new_name='reviews_rev_cliente_0e8e2e_idx',
            old_name='reviews_rev_cliente_3f8df6_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewerassignment',
            new_name='reviews_rev_cliente_7eac76_idx',
            old_name='reviews_rev_cliente_5c3d66_idx',
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='decision_type',
            field=models.CharField(choices=[('recommend_approve', 'Recomendar validação'), ('recommend_return', 'Recomendar devolução'), ('recommend_minor', 'Recomendar ajustes menores'), ('in_progress', 'Em andamento')], max_length=30),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewdecision',
            name='target_type',
            field=models.CharField(choices=[('resposta', 'Resposta'), ('texto_unico', 'Texto Único'), ('quadro', 'Quadro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reviewerassignment',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='reviewerassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
