# Generated by Django 5.1.5 on 2026-02-25

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import core.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0011_alter_usuario_role"),
        ("dynamicforms", "0004_alter_respostacampodinamico_owner_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("nome", models.CharField(max_length=255)),
                ("categoria", models.CharField(choices=[("formacao", "Formação"), ("avamec", "AVAMEC")], default="avamec", max_length=40)),
                ("descricao", models.TextField(blank=True)),
                ("objetivos", models.TextField(blank=True)),
                ("carga_horaria_total", models.PositiveIntegerField(default=0)),
                ("carga_presencial", models.PositiveIntegerField(default=0)),
                ("carga_sincrona", models.PositiveIntegerField(default=0)),
                ("carga_producao", models.PositiveIntegerField(default=0)),
                ("publicado", models.BooleanField(default=False)),
                ("regras_certificacao_json", models.JSONField(blank=True, default=dict)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursos", to="core.cliente")),
            ],
            options={
                "ordering": ("nome",),
                "indexes": [models.Index(fields=["cliente", "publicado"], name="courses_curs_cliente_390c96_idx")],
            },
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoAviso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("titulo", models.CharField(max_length=255)),
                ("corpo", models.TextField()),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursoavisos", to="core.cliente")),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="avisos", to="courses.curso")),
            ],
            options={"ordering": ("-publicado_em", "-created_at")},
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoCronogramaItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("semana", models.CharField(blank=True, max_length=120)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursocronogramaitems", to="core.cliente")),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cronograma_itens", to="courses.curso")),
            ],
            options={"ordering": ("ordem", "id")},
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoModulo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("titulo", models.CharField(max_length=255)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("tipo", models.CharField(choices=[("APRESENTACAO", "Apresentação"), ("MODULO", "Módulo"), ("BANCO_PLANOS", "Banco de Planos"), ("FORUM_GERAL", "Fórum Geral"), ("BIBLIOTECA", "Biblioteca"), ("ENTREGA_FINAL", "Entrega Final")], default="MODULO", max_length=30)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursomodulos", to="core.cliente")),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="modulos", to="courses.curso")),
            ],
            options={"ordering": ("ordem", "id")},
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoParticipacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("presenca_presencial", models.BooleanField(default=False)),
                ("encontros_sincronos_presentes", models.PositiveIntegerField(default=0)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursoparticipacaos", to="core.cliente")),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participacoes", to="courses.curso")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cursos_participacoes", to=settings.AUTH_USER_MODEL)),
            ],
            options={},
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoProgresso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("percentual", models.PositiveIntegerField(default=0)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursoprogressos", to="core.cliente")),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="progressos", to="courses.curso")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cursos_progressos", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [models.Index(fields=["cliente", "usuario"], name="courses_curs_cliente_b8e56c_idx")],
            },
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("ordem", models.PositiveIntegerField(default=0)),
                ("tipo", models.CharField(choices=[("VIDEO", "Vídeo"), ("TEXTO", "Texto"), ("CADERNO", "Caderno"), ("TAREFA", "Tarefa"), ("FORUM", "Fórum"), ("FORMULARIO", "Formulário"), ("CHECKLIST", "Checklist")], max_length=20)),
                ("titulo", models.CharField(max_length=255)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursoitems", to="core.cliente")),
                ("modulo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="courses.cursomodulo")),
            ],
            options={
                "ordering": ("ordem", "id"),
                "indexes": [models.Index(fields=["cliente", "tipo"], name="courses_curs_cliente_93b4e6_idx")],
            },
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PlanoAulaResposta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("ENVIADO", "Enviado")], default="RASCUNHO", max_length=20)),
                ("compartilhado_banco", models.BooleanField(default=False)),
                ("enviado_em", models.DateTimeField(blank=True, null=True)),
                ("bloqueado_em", models.DateTimeField(blank=True, null=True)),
                ("dados_cache_json", models.JSONField(blank=True, default=dict)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="planoaularespostas", to="core.cliente")),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planos_aula", to="courses.curso")),
                ("formulario", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="planos_aula", to="dynamicforms.formulariodinamico")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planos_aula_respostas", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
                "indexes": [
                    models.Index(fields=["cliente", "usuario", "curso"], name="courses_plan_cliente_4c734c_idx"),
                    models.Index(fields=["cliente", "status"], name="courses_plan_cliente_252154_idx"),
                ],
            },
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoCertificadoEmitido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("codigo", models.CharField(blank=True, default="", max_length=64, unique=True)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursocertificadoemitidos", to="core.cliente")),
                ("curso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="certificados_emitidos", to="courses.curso")),
                ("usuario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="certificados_curso_emitidos", to=settings.AUTH_USER_MODEL)),
            ],
            options={},
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="CursoProgressoItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("referencia_tipo", models.CharField(blank=True, max_length=50)),
                ("referencia_id", models.CharField(blank=True, max_length=64)),
                ("concluido_em", models.DateTimeField(auto_now_add=True)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursoprogressoitems", to="core.cliente")),
                ("item", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="progresso_itens", to="courses.cursoitem")),
                ("progresso", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="courses.cursoprogresso")),
            ],
            options={
                "indexes": [models.Index(fields=["cliente", "concluido_em"], name="courses_curs_cliente_6738be_idx")],
            },
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PlanoAulaPublicacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("ENVIADO", "Enviado"), ("APROVADO", "Aprovado"), ("PUBLICADO", "Publicado")], default="RASCUNHO", max_length=20)),
                ("allow_comments", models.BooleanField(default=True)),
                ("payload_json", models.JSONField(blank=True, default=dict)),
                ("autor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="planos_aula_publicacoes", to=settings.AUTH_USER_MODEL)),
                ("cliente", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="planoaulapublicacaos", to="core.cliente")),
                ("resposta_formulario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="publicacoes", to="courses.planoaularesposta")),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
                "indexes": [
                    models.Index(fields=["cliente", "status"], name="courses_plan_cliente_1d5031_idx"),
                    models.Index(fields=["cliente", "autor"], name="courses_plan_cliente_45329e_idx"),
                ],
            },
            managers=[
                ("objects", core.mixins.ClientScopedManager()),
                ("raw_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="cursoprogressoitem",
            constraint=models.UniqueConstraint(condition=models.Q(("item__isnull", False)), fields=("progresso", "item"), name="uniq_curso_progresso_item_por_item"),
        ),
        migrations.AlterUniqueTogether(
            name="cursoitem",
            unique_together={("modulo", "ordem", "titulo")},
        ),
        migrations.AlterUniqueTogether(
            name="cursomodulo",
            unique_together={("curso", "ordem", "tipo", "titulo")},
        ),
        migrations.AlterUniqueTogether(
            name="cursoparticipacao",
            unique_together={("curso", "usuario")},
        ),
        migrations.AlterUniqueTogether(
            name="cursoprogresso",
            unique_together={("curso", "usuario")},
        ),
        migrations.AlterUniqueTogether(
            name="cursocertificadoemitido",
            unique_together={("curso", "usuario")},
        ),
    ]
