# Generated by Django 5.0.2 on 2026-02-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _rename_index_if_supported(old_name: str, new_name: str):
    def forwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')

    def backwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}";')

    return migrations.RunPython(forwards, backwards)


def safe_rename_index(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            _rename_index_if_supported(old_name, new_name),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                old_name=old_name,
                new_name=new_name,
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_usuario_role'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pontuacao', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('comentario', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('escola', models.CharField(blank=True, max_length=255)),
                ('etapa_modalidade', models.CharField(blank=True, max_length=255)),
                ('componente_curricular', models.CharField(blank=True, max_length=255)),
                ('unidade_tematica', models.CharField(blank=True, max_length=255)),
                ('habilidades', models.JSONField(blank=True, default=list)),
                ('objetivos', models.TextField(blank=True)),
                ('conteudos', models.TextField(blank=True)),
                ('metodologia', models.TextField(blank=True)),
                ('recursos', models.TextField(blank=True)),
                ('avaliacao', models.TextField(blank=True)),
                ('estrategias_recomposicao', models.TextField(blank=True)),
                ('estrategias_inclusivas', models.TextField(blank=True)),
                ('referencias', models.TextField(blank=True)),
                ('metas_ppp', models.JSONField(blank=True, default=list)),
                ('habilidades_referencial', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_revisao', 'Em revisão'), ('aprovado', 'Aprovado'), ('publicado', 'Publicado')], default='rascunho', max_length=20)),
            ],
            options={
                'ordering': ('-updated_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='RubricaCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('pontuacao_maxima', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.AlterModelManagers(
            name='curso',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursoaviso',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursocertificadoemitido',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursocronogramaitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursoitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursomodulo',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursoparticipacao',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursoprogresso',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='cursoprogressoitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='planoaulapublicacao',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='planoaularesposta',
            managers=[
            ],
        ),
        safe_rename_index('curso', 'courses_curs_cliente_390c96_idx', 'courses_cur_cliente_d28afb_idx'),
        safe_rename_index('cursoitem', 'courses_curs_cliente_93b4e6_idx', 'courses_cur_cliente_886e67_idx'),
        safe_rename_index('cursoprogresso', 'courses_curs_cliente_b8e56c_idx', 'courses_cur_cliente_c693ed_idx'),
        safe_rename_index('cursoprogressoitem', 'courses_curs_cliente_6738be_idx', 'courses_cur_cliente_7bdeea_idx'),
        safe_rename_index('planoaulapublicacao', 'courses_plan_cliente_1d5031_idx', 'courses_pla_cliente_011610_idx'),
        safe_rename_index('planoaulapublicacao', 'courses_plan_cliente_45329e_idx', 'courses_pla_cliente_0c6c02_idx'),
        safe_rename_index('planoaularesposta', 'courses_plan_cliente_4c734c_idx', 'courses_pla_cliente_796e13_idx'),
        safe_rename_index('planoaularesposta', 'courses_plan_cliente_252154_idx', 'courses_pla_cliente_2c9645_idx'),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_plataforma',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_presencial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria_sincrona',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(default='rascunho', max_length=30),
        ),
        migrations.AddField(
            model_name='cursoitem',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cursomodulo',
            name='carga_horaria',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cursomodulo',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursoaviso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursocertificadoemitido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursocronogramaitem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursoitem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursoitem',
            name='tipo',
            field=models.CharField(choices=[('VIDEO', 'Vídeo'), ('TEXTO', 'Texto'), ('CADERNO', 'Caderno'), ('TAREFA', 'Tarefa'), ('FORUM', 'Fórum'), ('FORMULARIO', 'Formulário'), ('CHECKLIST', 'Checklist'), ('ATIVIDADE', 'Atividade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cursomodulo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursoparticipacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursoprogresso',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='cursoprogressoitem',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='planoaulapublicacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='planoaularesposta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='avaliacaoplano',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_planos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacaoplano',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_estruturados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='planoaula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_estruturados', to='courses.curso'),
        ),
        migrations.AddField(
            model_name='avaliacaoplano',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='courses.planoaula'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='courses.curso'),
        ),
        migrations.AddField(
            model_name='rubricacriterio',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='rubricacriterio',
            name='rubrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='courses.rubrica'),
        ),
        migrations.AddField(
            model_name='avaliacaoplano',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='courses.rubricacriterio'),
        ),
        migrations.AddIndex(
            model_name='planoaula',
            index=models.Index(fields=['cliente', 'curso', 'autor'], name='courses_pla_cliente_daef13_idx'),
        ),
        migrations.AddIndex(
            model_name='planoaula',
            index=models.Index(fields=['cliente', 'status'], name='courses_pla_cliente_49beaa_idx'),
        ),
        migrations.AddIndex(
            model_name='planoaula',
            index=models.Index(fields=['cliente', 'escola'], name='courses_pla_cliente_268bf0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rubrica',
            unique_together={('cliente', 'curso', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='rubricacriterio',
            unique_together={('rubrica', 'nome')},
        ),
        migrations.AddIndex(
            model_name='avaliacaoplano',
            index=models.Index(fields=['cliente', 'plano', 'avaliador'], name='courses_ava_cliente_9dc8df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacaoplano',
            unique_together={('plano', 'avaliador', 'criterio')},
        ),
    ]
