# Generated by Django 5.1.13 on 2025-11-25 02:27

import consultas.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_usersessionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('token_acesso', models.CharField(default=consultas.models._token, max_length=32, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('pdf', models.FileField(upload_to=consultas.models._upload_to)),
                ('data_publicacao', models.DateField()),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('pergunta_votacao', models.CharField(blank=True, max_length=255)),
                ('opcoes_votacao', models.JSONField(blank=True, default=list)),
                ('ativa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('criada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_publicas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_publicacao', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ManifestacaoPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario', models.TextField()),
                ('voto', models.CharField(blank=True, max_length=255)),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('contato_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestacoes', to='consultas.consultapublica')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='consultapublica',
            index=models.Index(fields=['cliente', 'slug'], name='consultas_c_cliente_c54a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='consultapublica',
            index=models.Index(fields=['cliente', 'data_publicacao'], name='consultas_c_cliente_f4978a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consultapublica',
            unique_together={('cliente', 'slug')},
        ),
        migrations.AddIndex(
            model_name='manifestacaopublica',
            index=models.Index(fields=['cliente', 'consulta'], name='consultas_m_cliente_f859c6_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaopublica',
            index=models.Index(fields=['cliente', 'consulta', 'pagina'], name='consultas_m_cliente_0004f8_idx'),
        ),
        migrations.AddIndex(
            model_name='manifestacaopublica',
            index=models.Index(fields=['created_at'], name='consultas_m_created_0b293e_idx'),
        ),
    ]
