# Generated by Django 5.1.5 on 2026-02-19 02:44

from django.db import migrations, models


def forwards(apps, schema_editor):
    """Convert old single-question fields into the new JSON array format."""
    ConsultaPublica = apps.get_model("consultas", "ConsultaPublica")
    for cp in ConsultaPublica.objects.all():
        perguntas = []
        if cp.pergunta_votacao:
            perguntas.append({
                "pergunta": cp.pergunta_votacao,
                "opcoes": cp.opcoes_votacao or [],
            })
        cp.perguntas_votacao = perguntas
        cp.save(update_fields=["perguntas_votacao"])

    ManifestacaoPublica = apps.get_model("consultas", "ManifestacaoPublica")
    for mp in ManifestacaoPublica.objects.all():
        votos = []
        if mp.voto:
            votos.append(mp.voto)
        mp.votos = votos
        mp.save(update_fields=["votos"])


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        # 1. Add new fields (keeping old ones temporarily)
        migrations.AddField(
            model_name='consultapublica',
            name='perguntas_votacao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='manifestacaopublica',
            name='votos',
            field=models.JSONField(blank=True, default=list),
        ),

        # 2. Copy data from old fields to new ones
        migrations.RunPython(forwards, migrations.RunPython.noop),

        # 3. Remove old fields
        migrations.RemoveField(
            model_name='consultapublica',
            name='opcoes_votacao',
        ),
        migrations.RemoveField(
            model_name='consultapublica',
            name='pergunta_votacao',
        ),
        migrations.RemoveField(
            model_name='manifestacaopublica',
            name='voto',
        ),
    ]
