# Generated by Django 5.1.5 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultas", "0002_multi_perguntas_votacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="manifestacaopublica",
            name="area_atuacao_profissional",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
