# Generated by Django 5.1.15 on 2026-05-27 22:01

import consultas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0005_formularioinscricao_inscricaopublica'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inscricaopublica',
            new_name='consultas_i_cliente_978a81_idx',
            old_name='consultas_i_cliente_form_idx',
        ),
        migrations.RenameIndex(
            model_name='inscricaopublica',
            new_name='consultas_i_created_b4228b_idx',
            old_name='consultas_i_created_at_idx',
        ),
        migrations.AddField(
            model_name='consultapublica',
            name='imagem_hero',
            field=models.ImageField(blank=True, null=True, upload_to=consultas.models._upload_hero_to),
        ),
    ]
