# Generated by Django 5.1.15 on 2026-05-27 22:49

import consultas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_rename_consultas_i_cliente_form_idx_consultas_i_cliente_978a81_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioinscricao',
            name='imagem_hero',
            field=models.ImageField(blank=True, null=True, upload_to=consultas.models._upload_inscricao_hero_to),
        ),
    ]
