# Generated by Django 5.1.13 on 2025-12-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_alter_exportjob_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='payload_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='alvo_tipo',
            field=models.CharField(choices=[('texto_unico', 'Texto Único'), ('quadro', 'Quadro'), ('resposta', 'Resposta'), ('colecao', 'Coleção')], max_length=20),
        ),
    ]
