# Generated by Django 5.1.5 on 2026-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0003_exportjob_payload_json_alter_exportjob_alvo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportjob',
            name='alvo_tipo',
            field=models.CharField(choices=[('texto_unico', 'Texto Único'), ('quadro', 'Quadro'), ('resposta', 'Resposta'), ('colecao', 'Coleção'), ('relatorio', 'Relatório')], max_length=20),
        ),
    ]
