# Generated by Django 5.1.13 on 2025-10-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_audit_cliente_37c01d_idx_core_auditl_cliente_c6c50f_idx_and_more'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celulaquadro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='quadro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
    ]
