# Generated by Django 5.1.5 on 2026-01-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_throttleblock"),
        ("core", "0008_enable_reviews_flag"),
        ("workshop", "0002_alter_celulaquadro_cliente_alter_quadro_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadroColuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coluna', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='workshop.quadro')),
            ],
            options={
                'ordering': ('coluna',),
                'unique_together': {('quadro', 'coluna')},
            },
        ),
        migrations.CreateModel(
            name='QuadroLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('linha', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('quadro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='workshop.quadro')),
            ],
            options={
                'ordering': ('linha',),
                'unique_together': {('quadro', 'linha')},
            },
        ),
    ]
