# Generated by Django 5.1.5 on 2026-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_quadrocoluna_quadrolinha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quadrocoluna',
            options={'ordering': ('ordem', 'coluna')},
        ),
        migrations.AlterModelOptions(
            name='quadrolinha',
            options={'ordering': ('ordem', 'linha')},
        ),
        migrations.AddField(
            model_name='quadrocoluna',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quadrolinha',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
