# Generated by Django 5.1.5 on 2026-01-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_area'),
        ('workshop', '0004_alter_quadrocoluna_options_alter_quadrolinha_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadro',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quadros', to='curriculum.area'),
        ),
    ]
