# Generated by Django 5.1.13 on 2025-10-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_audit_cliente_37c01d_idx_core_auditl_cliente_c6c50f_idx_and_more'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gt',
            options={'ordering': ('nome',), 'verbose_name': 'Grupo de Trabalho', 'verbose_name_plural': 'Grupos de Trabalho'},
        ),
        migrations.RenameIndex(
            model_name='resposta',
            new_name='curriculum__cliente_cd9187_idx',
            old_name='curr_res_client_8be6f8_idx',
        ),
        migrations.RenameIndex(
            model_name='textounico',
            new_name='curriculum__cliente_46cd17_idx',
            old_name='curr_text_cliente_3baf05_idx',
        ),
        migrations.AlterField(
            model_name='anexo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='gt',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='textounico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
    ]
