# Generated by Django 5.1.13 on 2025-10-06 17:01

import django.db.models.deletion
from django.db import migrations, models


def _rename_index_if_supported(old_name: str, new_name: str):
    def forwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')

    def backwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}";')

    return migrations.RunPython(forwards, backwards)


def safe_rename_index(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            _rename_index_if_supported(old_name, new_name),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                old_name=old_name,
                new_name=new_name,
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_audit_cliente_37c01d_idx_core_auditl_cliente_c6c50f_idx_and_more'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gt',
            options={'ordering': ('nome',), 'verbose_name': 'Grupo de Trabalho', 'verbose_name_plural': 'Grupos de Trabalho'},
        ),
        safe_rename_index('resposta', 'curr_res_client_8be6f8_idx', 'curriculum__cliente_cd9187_idx'),
        safe_rename_index('textounico', 'curr_text_cliente_3baf05_idx', 'curriculum__cliente_46cd17_idx'),
        migrations.AlterField(
            model_name='anexo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='gt',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='textounico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
    ]
