# Generated by Django 5.1.13 on 2025-10-29 00:18

import django.db.models.deletion
from django.db import migrations, models


def safe_rename_index(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunSQL(
                sql=f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";',
                reverse_sql=f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}";',
            ),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                old_name=old_name,
                new_name=new_name,
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_core_audit_cliente_37c01d_idx_core_auditl_cliente_c6c50f_idx_and_more'),
        ('curriculum', '0003_textocolaborativo'),
    ]

    operations = [
        safe_rename_index('textocolaborativo', 'textocolab_cliente_gt_idx', 'curriculum__cliente_813d28_idx'),
        migrations.AddField(
            model_name='pergunta',
            name='gts',
            field=models.ManyToManyField(blank=True, help_text='Selecione um ou mais GTs aos quais esta pergunta se aplica. Deixe em branco para aplicar a todos.', related_name='perguntas', to='curriculum.gt'),
        ),
        migrations.AlterField(
            model_name='textocolaborativo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente'),
        ),
    ]
