# Generated by Django 5.1.13 on 2025-10-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_rename_textocolab_cliente_gt_idx_curriculum__cliente_813d28_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(default=1, max_length=255, verbose_name='Tarefa'),
            preserve_default=False,
        ),
    ]
