# Generated by Django 5.1.13 on 2026-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_textocolaborativo_pergunta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='textocolaborativo',
            new_name='curriculum__cliente_effb86_idx',
            old_name='curriculum_textocolab_cli_gt_perg_idx',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_desenvolvimento', 'Em desenvolvimento'), ('em_revisao', 'Em revisão'), ('concluida', 'Concluída')], default='rascunho', max_length=20),
        ),
    ]
