# Generated by Django 5.1.13 on 2026-01-06 02:20

from django.db import migrations, models


def _rename_index_if_supported(old_name: str, new_name: str):
    def forwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{old_name}" RENAME TO "{new_name}";')

    def backwards(apps, schema_editor):
        if schema_editor.connection.vendor == "sqlite":
            return
        schema_editor.execute(f'ALTER INDEX IF EXISTS "{new_name}" RENAME TO "{old_name}";')

    return migrations.RunPython(forwards, backwards)


def safe_rename_index(model_name: str, old_name: str, new_name: str):
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            _rename_index_if_supported(old_name, new_name),
        ],
        state_operations=[
            migrations.RenameIndex(
                model_name=model_name,
                old_name=old_name,
                new_name=new_name,
            ),
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_textocolaborativo_pergunta'),
    ]

    operations = [
        safe_rename_index('textocolaborativo', 'curriculum_textocolab_cli_gt_perg_idx', 'curriculum__cliente_effb86_idx'),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_desenvolvimento', 'Em desenvolvimento'), ('em_revisao', 'Em revisão'), ('concluida', 'Concluída')], default='rascunho', max_length=20),
        ),
    ]
