# Generated by Django 5.1.5 on 2026-01-21 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_throttleblock"),
        ("core", "0008_enable_reviews_flag"),
        ("curriculum", "0007_rename_curriculum_textocolab_cli_gt_perg_idx_curriculum__cliente_effb86_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("nome", models.CharField(max_length=255)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="core.cliente",
                    ),
                ),
                ("gts", models.ManyToManyField(blank=True, related_name="areas", to="curriculum.gt")),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "ordering": ("nome",),
                "unique_together": {("cliente", "nome")},
            },
        ),
    ]
