# Generated by Django 5.1.5 on 2026-03-13 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_usuario_escola_and_roles'),
        ('curriculum', '0010_escola'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titulo', models.CharField(default='Projeto Político-Pedagógico', max_length=255)),
                ('conteudo_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('em_elaboracao', 'Em elaboração'), ('concluido', 'Concluído')], default='em_elaboracao', max_length=30)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.cliente')),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppps_concluidos', to=settings.AUTH_USER_MODEL)),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ppp', to='curriculum.escola')),
                ('ultima_edicao_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppps_editados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PPP',
                'verbose_name_plural': 'PPPs',
                'ordering': ('escola__nome',),
                'indexes': [models.Index(fields=['cliente', 'status'], name='curriculum__cliente_6e9c56_idx'), models.Index(fields=['cliente', 'escola'], name='curriculum__cliente_192d07_idx')],
            },
        ),
    ]
