# Generated by Django 5.2.11 on 2026-05-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_redundant_indexes_add_gt_unique'),
        ('curriculum', '0011_ppp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resposta',
            name='curriculum__cliente_cd9187_idx',
        ),
        migrations.RemoveIndex(
            model_name='textounico',
            name='curriculum__cliente_46cd17_idx',
        ),
        migrations.AlterUniqueTogether(
            name='gt',
            unique_together={('cliente', 'nome', 'etapa')},
        ),
    ]
