# Generated by Django 5.1.15 on 2026-05-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_muraldownloadregistro'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='muralarquivoenvio',
            new_name='notificatio_cliente_e03496_idx',
            old_name='notificatio_cliente_4d63d2_idx',
        ),
        migrations.RenameIndex(
            model_name='muralarquivoenvio',
            new_name='notificatio_cliente_e29ab6_idx',
            old_name='notificatio_cliente_0c86fb_idx',
        ),
        migrations.RenameIndex(
            model_name='muraldownloadregistro',
            new_name='notificatio_cliente_4b8433_idx',
            old_name='notificatio_cliente_02716b_idx',
        ),
        migrations.RenameIndex(
            model_name='muraldownloadregistro',
            new_name='notificatio_cliente_1ee900_idx',
            old_name='notificatio_cliente_2d2101_idx',
        ),
    ]
